language: rust
rust:
- stable
- nightly
before_script:
- pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
- travis-cargo build
# tests currently require unstable features of tempfile crate, and can't run on stable
- if `test $TRAVIS_RUST_VERSION = nightly`; then travis-cargo test; fi
- travis-cargo doc
after_success:
# upload docs with nightly, as these look better
- if `test $TRAVIS_RUST_VERSION = nightly`; then travis-cargo doc-upload; fi
env:
  global:
    secure: VJOOFTlmkCYlvdS1fCZ9dATh3H49rdK5wZZTCa6GmJgxUiCAmDUIYvVIdhJQkYrPygpawRSp5z4uWwN2mAWRGBnAOxCbaB6gNnXQGBGvcs+QhyW7m+fMtmXJ+DIW7Sd012VijX56Wr2mbiKEfCXS4xd5QcmdKng/2NKz1zmqFD+9UB9r7VnushMgRyWvvt89FDrhiYutf3vPkNTgDBxsC+mp7P9FYYdPvx1jQL2X1eK9+qeuB4iE7BzRifsK1/acXcgyMjsxUHswl1adQ9tNm/epfZo1I/mdCBtTVVXGUMYI8333EUIMlZQMPbnNOZ0U4lsEFRQ4MqSmq2p//IKKNU7KJaEak3da/wxW5SMzry0r69JQrmvQfj6AmQ8CqChgeSGB3rf/peK72VmDDPk2k1wLcr0OTvags0QD2NFpB7ksqBpZRzxJzz90IUWc0TmYNiWrU5BJjGbelirTEp9svWJM2MDnQKHKWo5lEeN85QwOuvkXDg3Puft/fhgdYz/kVRdUPjnxCWoO8IA8tz9pqgAt7+8zbWChYOosUDeooclw7ab9cPlN28233DtjsVlUwvqxwgooSJiebnrGewdn7Z6IlDaMmg44Z5wgheMExb+fX8dITB6hAMKTyuPQDow6gZcfraXL37sLLFzdNL1Bh9FFi82GTp1CCWwdMDF5slE=
