[package]
name        = "file-lock"
version     = "1.1.18"
authors     = ["Alfie John <alfie@alfie.wtf>", "Sebastian Thiel <byronimo@gmail.com>"]
description = "File locking via POSIX advisory record locks"
license     = "MIT"

documentation = "http://docs.rs/file-lock/"
homepage      = "https://crates.io/crates/file-lock"
repository    = "https://gitlab.com/alfiedotwtf/file-lock"

build   = "build.rs"

[dependencies]
libc   = "0.2.42"
mktemp = "0.3.1"
nix    = "0.11.0"

[build-dependencies]
gcc = "0.3.54"
