[package]
name = "file-lock"
version = "0.0.14"
authors = ["Alfie John <alfie@alfie.wtf>"]
description = "File locking via POSIX advisory record locks"

documentation = "https://www.alfie.wtf/rust-doc/file_lock/"
homepage = "https://crates.io/crates/file-lock"
repository = "https://github.com/alfiedotwtf/file-lock"

license = "LGPL-3.0"

build = "build.rs"

[lib]
name = "file_lock"

[dependencies]
libc = "*"

[build-dependencies]
gcc = "*"
