[package]
name = "file-lock"
version = "0.0.5"
authors = ["Alfie John <alfie@alfie.wtf>"]

description = "File locking via POSIX advisory record locks"
repository = "https://github.com/alfiedotwtf/file-lock"
license = "GPL-3.0"

build = "build.rs"

[lib]
name = "file_lock"

[build-dependencies]
gcc = "*"
